language: python
python:
  - "3.6"
services:
  - postgresql

env:
  APP_ENV: testing
  SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://localhost/discover_weekly_checklist

install:
  - pip3 install -r requirements.txt

before_script:
  - psql -c 'create database discover_weekly_checklist_test;' -U postgres

script:
  - python3 manage.py create_db
  - python3 manage.py run_tests